2019/11/17 19:06:54 [error] 17#17: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidConfigException: Unknown component ID: i18n in /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php:139
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('i18n', true)
#1 /var/www/app/vendor/yiisoft/yii2/base/Application.php(580): yii\base\Module->get('i18n')
#2 /var/www/app/vendor/yiisoft/yii2/BaseYii.php(538): yii\base\Application->getI18n()
#3 /var/www/app/vendor/yiisoft/yii2/validators/IpValidator.php(218): yii\BaseYii::t('yii', '{attribute} mus...')
#4 /var/www/app/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\validators\IpValidator->init()
#5 /var/www/app/vendor/yiisoft/yii2/web/Request.php(342): yii\base\BaseObject->__construct()
#6 /var/www/app/vendor/yiisoft/yii2/web/Request.php(316): yii\web\Request->getIpValidator()
#7 /var/www/app/vendor/yiisoft/yii2/web/Request.php(294): yii\web\Request->getTrustedHeaders()
#8 /var/www/app/vendor/yiisoft/yii2/web/Request.p" while reading upstream, client: 172.27.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.247"
2019/11/17 19:06:54 [error] 17#17: *2 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidConfigException: Unknown component ID: i18n in /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php:139
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('i18n', true)
#1 /var/www/app/vendor/yiisoft/yii2/base/Application.php(580): yii\base\Module->get('i18n')
#2 /var/www/app/vendor/yiisoft/yii2/BaseYii.php(538): yii\base\Application->getI18n()
#3 /var/www/app/vendor/yiisoft/yii2/validators/IpValidator.php(218): yii\BaseYii::t('yii', '{attribute} mus...')
#4 /var/www/app/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\validators\IpValidator->init()
#5 /var/www/app/vendor/yiisoft/yii2/web/Request.php(342): yii\base\BaseObject->__construct()
#6 /var/www/app/vendor/yiisoft/yii2/web/Request.php(316): yii\web\Request->getIpValidator()
#7 /var/www/app/vendor/yiisoft/yii2/web/Request.php(294): yii\web\Request->getTrustedHeaders()
#8 /var/www/app/vendor/yiisoft/yii2/web/Request.p" while reading upstream, client: 172.27.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "[80fe:0000:0000:0000:9618:758c:2bbc:27ae]"
2019/11/17 19:07:14 [error] 17#17: *5 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidConfigException: Unknown component ID: i18n in /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php:139
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('i18n', true)
#1 /var/www/app/vendor/yiisoft/yii2/base/Application.php(580): yii\base\Module->get('i18n')
#2 /var/www/app/vendor/yiisoft/yii2/BaseYii.php(538): yii\base\Application->getI18n()
#3 /var/www/app/vendor/yiisoft/yii2/validators/IpValidator.php(218): yii\BaseYii::t('yii', '{attribute} mus...')
#4 /var/www/app/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\validators\IpValidator->init()
#5 /var/www/app/vendor/yiisoft/yii2/web/Request.php(342): yii\base\BaseObject->__construct()
#6 /var/www/app/vendor/yiisoft/yii2/web/Request.php(316): yii\web\Request->getIpValidator()
#7 /var/www/app/vendor/yiisoft/yii2/web/Request.php(294): yii\web\Request->getTrustedHeaders()
#8 /var/www/app/vendor/yiisoft/yii2/web/Request.p" while reading upstream, client: 172.27.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost"
2019/11/17 19:31:39 [error] 17#17: *2 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/common/config/main-local.php on line 27. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidConfigException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\InvalidConfigException))
#4 {main}
Previous exception:
yii\base\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php:205
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/di/ServiceLocator.php(261): yii\di\ServiceLocator->set('params', Array)
#1 /var/www/app/v" while reading upstream, client: 172.27.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost"
2019/12/02 13:11:02 [error] 19#19: *94 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 53. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 53. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 13:11:36 [error] 19#19: *96 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 53. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 53. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 13:24:23 [error] 16#16: *1 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 13:43:40 [error] 16#16: *85 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 15:08:17 [error] 18#18: *1 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 15:13:55 [error] 18#18: *25 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/02 15:17:32 [error] 18#18: *43 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:14:06 [error] 17#17: *5 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:16:23 [error] 17#17: *15 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:19:52 [error] 17#17: *29 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:30:09 [error] 17#17: *77 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:32:01 [error] 17#17: *85 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:34:49 [error] 17#17: *99 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:38:46 [error] 17#17: *121 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:42:39 [error] 17#17: *166 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:44:03 [error] 17#17: *176 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:45:39 [error] 17#17: *182 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:47:23 [error] 17#17: *192 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:50:23 [error] 17#17: *206 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:53:11 [error] 17#17: *222 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:55:44 [error] 17#17: *232 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/04 19:59:03 [error] 17#17: *250 upstream timed out (110: Operation timed out) while reading upstream, client: 172.18.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1"
2019/12/14 21:08:56 [error] 17#17: *20 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:10:11 [error] 17#17: *18 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:10:33 [error] 17#17: *69 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:11:35 [error] 16#16: *10 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:11:55 [error] 16#16: *54 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:15:38 [error] 16#16: *122 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:17:32 [error] 16#16: *182 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:25:28 [error] 16#16: *261 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:27:11 [error] 16#16: *14 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:27:39 [error] 16#16: *65 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:28:00 [error] 16#16: *110 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:30:06 [error] 16#16: *26 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:32:11 [error] 16#16: *17 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:32:47 [error] 16#16: *58 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:33:24 [error] 16#16: *115 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:34:36 [error] 16#16: *165 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:35:48 [error] 16#16: *216 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2019/12/14 21:37:54 [error] 16#16: *279 access forbidden by rule, client: 172.18.0.1, server: dev.scaner.app, request: "GET /.git/HEAD HTTP/1.1", host: "172.17.0.1"
2020/02/12 19:57:19 [error] 17#17: *182 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 10:16:01 [error] 18#18: *21 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock", host: "dev.localhost.soft"
2020/02/15 10:36:48 [error] 18#18: *134 open() "/var/www/app/frontend/web/screenshots/http__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:36:48 [error] 18#18: *133 open() "/var/www/app/frontend/web/screenshots/https__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:36:48 [error] 18#18: *134 open() "/var/www/app/frontend/web/screenshots/https__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:36:48 [error] 19#19: *136 open() "/var/www/app/frontend/web/screenshots/http__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:36:48 [error] 21#21: *137 open() "/var/www/app/frontend/web/screenshots/http__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:36:48 [error] 18#18: *133 open() "/var/www/app/frontend/web/screenshots/https__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 18#18: *145 open() "/var/www/app/frontend/web/screenshots/https__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 19#19: *147 open() "/var/www/app/frontend/web/screenshots/http__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 18#18: *144 open() "/var/www/app/frontend/web/screenshots/https__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 19#19: *147 open() "/var/www/app/frontend/web/screenshots/http__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 18#18: *145 open() "/var/www/app/frontend/web/screenshots/http__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:37:54 [error] 19#19: *148 open() "/var/www/app/frontend/web/screenshots/https__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 18#18: *154 open() "/var/www/app/frontend/web/screenshots/https__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 19#19: *157 open() "/var/www/app/frontend/web/screenshots/https__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 21#21: *160 open() "/var/www/app/frontend/web/screenshots/https__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 19#19: *158 open() "/var/www/app/frontend/web/screenshots/http__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 19#19: *159 open() "/var/www/app/frontend/web/screenshots/http__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:22 [error] 19#19: *155 open() "/var/www/app/frontend/web/screenshots/http__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 21#21: *166 open() "/var/www/app/frontend/web/screenshots/http__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 19#19: *165 open() "/var/www/app/frontend/web/screenshots/https__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__93_184_216_34.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 20#20: *168 open() "/var/www/app/frontend/web/screenshots/http__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 20#20: *167 open() "/var/www/app/frontend/web/screenshots/https__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 20#20: *167 open() "/var/www/app/frontend/web/screenshots/https__example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:38:32 [error] 18#18: *163 open() "/var/www/app/frontend/web/screenshots/http__www_example_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__www_example_com.png HTTP/1.1", host: "localhost", referrer: "http://localhost/scan/scanresult?id=2909"
2020/02/15 10:39:33 [error] 18#18: *178 open() "/var/www/app/frontend/web/screenshots/http__93_184_216_34.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/http__93_184_216_34.png HTTP/1.1", host: "localhost"
2020/02/15 11:23:08 [error] 20#20: *30 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 12:13:11 [error] 20#20: *337 open() "/var/www/app/frontend/web/screenshots/https__esaf2020_rsaconference_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__esaf2020_rsaconference_com.png HTTP/1.1", host: "localhost"
2020/02/15 12:25:01 [error] 20#20: *399 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock", host: "dev.localhost.soft"
2020/02/15 13:22:49 [error] 20#20: *24 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 13:26:05 [error] 20#20: *58 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 13:34:06 [error] 20#20: *278 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 13:34:35 [error] 20#20: *257 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 13:39:48 [error] 20#20: *320 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 14:45:05 [error] 20#20: *836 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 14:54:04 [error] 17#17: *51 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 14:54:39 [error] 17#17: *45 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 14:57:03 [error] 17#17: *77 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 14:58:03 [error] 17#17: *96 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:01:03 [error] 17#17: *239 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:01:31 [error] 17#17: *229 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:04:03 [error] 17#17: *269 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 46. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 46. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:07:04 [error] 17#17: *294 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/app/frontend/models/Nmap.php on line 47. in /var/www/app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/app/vendor/yiisoft/yii" while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/nmap HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:13:15 [error] 17#17: *531 directory index of "/var/www/app/frontend/web/screenshots/" is forbidden, client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/ HTTP/1.1", host: "localhost"
2020/02/15 15:17:39 [error] 17#17: *557 open() "/var/www/app/frontend/web/screenshots/https__mail_ns1_xml-sitemaps_com.png" failed (13: Permission denied), client: 172.20.0.1, server: dev.scaner.app, request: "GET /screenshots/https__mail_ns1_xml-sitemaps_com.png HTTP/1.1", host: "localhost"
2020/02/15 15:24:37 [error] 17#17: *29 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
2020/02/15 15:37:05 [error] 19#19: *18 upstream timed out (110: Operation timed out) while reading upstream, client: 127.0.0.1, server: dev.scaner.app, request: "POST /scan/amass HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "dev.localhost.soft"
